name: Build and test


on:
  push:
    branches:
     - main

  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, edited]

  workflow_dispatch: # allows manual trigger

env:
  RUST_FMT_VERSION: nightly-2023-04-01-x86_64-unknown-linux-gnu

jobs:

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Run cargo fmt
        run: |
          rustup +${{ env.RUST_FMT_VERSION }} component add rustfmt
          cargo +${{ env.RUST_FMT_VERSION }} fmt --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Clippy
        run: |
          rustup component add clippy
      - name: Run Clippy
        run: |
          cargo clippy --all-targets --all-features --no-deps -- -D warnings

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Run tests
        run: |
          cargo test --all-features --release