name: Release Concordium Rust SDK

on:

  workflow_dispatch: # allows manual trigger

  push:
    tags:
      - release/concordium-rust-sdk/*

env:
  TAG: ${{ github.ref_name }}

jobs:

  ## Concordium Rust SDK Release Build
  concordium-rust-sdk-release:
    name: concordium-rust-sdk:release
    runs-on: ubuntu-latest
    environment: release

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Validate that the tag version matches the version in Cargo.toml
      - name: validate tag version has correct matching tag
        run: |
          echo "Validating tag version $TAG matches expected version from Cargo.toml"
          EXPECTED_VERSION_FROM_CARGO=$(yq .package.version ./Cargo.toml)
          TAG_VERSION_NUMBER=${TAG##release/concordium-rust-sdk/}
          
          # Check if the tag version number matches the expected version from Cargo.toml
          if [ "$TAG_VERSION_NUMBER" != "$EXPECTED_VERSION_FROM_CARGO" ]; then
            echo "version tagged: $TAG_VERSION_NUMBER  does not match cargo version: $EXPECTED_VERSION_FROM_CARGO. Exiting."
            exit 1
          else
            echo "Tag version number matches expected version from Cargo.toml. Proceeding with release."
          fi

      # Publish to crates.io
      - name: Publish to crates.io
        env: release
          CARGO_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          echo "Publishing Concordium Rust SDK to crates.io for version: $TAG_VERSION"
          cargo publish --token $CARGO_TOKEN --locked