name: Release Concordium Rust SDK

on:

  workflow_dispatch: # allows manual trigger

  ## TODO remove later - this is to test on each push to my branch
  push:
    branches: 
      - feature/COR1640-release-pipeline
    tags:
      - release/concordium-rust-sdk/*

env:
  RUST_FMT: nightly-2023-04-01-x86_64-unknown-linux-gnu
  RUST_VERSION: "1.85"
  #CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}

jobs:
  
  ## rust formatting checks
  rust-standard-checks:
    name: rust:checks
    runs-on: ubuntu-latest
    steps:
      # Checkout the code with submodules recursive
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # RustFmt checks
      - name: Rust Formatter
        run: |
          rustup default $RUST_FMT
          rustup component add rustfmt
          cargo fmt -- --color=always --check

      # Clippy checks
      - name: Clippy
        run: |
          rustup default $RUST_VERSION
          rustup component add clippy
          cargo clippy --color=always --all-targets --all-features -- -D warnings
          # Examples can be large with a lot of debug info due to tokio. So we
          # disable debug info generation.
          RUSTFLAGS="-C debuginfo=0" cargo test --all-targets --all-features
      
      - name: Compilation Check
        run: |
          rustup default $RUST_VERSION
          cargo check --all-targets --all-features 

  

  #release-rust-sdk:
  #  runs-on: ubuntu-latest
  #  #environment: release
  #  steps:
  #    - name: Checkout code
  #      uses: actions/checkout@v4
#
  #    - name: Set up Rust
  #      uses: actions/setup-rust@v1
  #      with:
  #        rust-version: stable
#
  #    - name: Build
  #      run: cargo build --release
#
  #    - name: Run tests
  #      run: cargo test --release


#     - name: Publish to crates.io
#       env:
#         CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
#       run: cargo publish --token $CARGO_REGISTRY_TOKEN --no-verify
#
#     - name: Create GitHub Release
#       uses: softprops/action-gh-release@v2
#       with:
#         tag_name: ${{ github.ref_name }}
#         name: Concordium Rust SDK ${{ github.ref_name }}
#         body: |
#           See CHANGELOG.md for details.

